version: '3.9'
services:
  mongo_db:
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    depends_on:
      - mongo_db
    ports:
      - 3010:3010
    environment:
      DB_URL: mongodb://mongo_db:27017/mongo_data
      jwtPrivateKey: helloWorld
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
volumes:
  mongo_data:
